[
    {
        "id": 1,
        "subject": "Lab-10",
        "bug_id": "3237-303406",
        "binary_path": "303406",
        "source_file": "303406_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "2",
            "public_14",
            "public_15",
            "public_16",
            "public_18",
            "public_19",
            "public_20"
        ],
        "passing_test": [
            "1",
            "3",
            "public_10",
            "public_12",
            "public_13",
            "public_17",
            "public_4",
            "public_5",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "count_neg": 7,
        "count_pos": 12,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3237.1.txt",
            "test/in.3237.2.txt",
            "test/in.3237.3.txt",
            "test/in.3237.public_10.txt",
            "test/in.3237.public_12.txt",
            "test/in.3237.public_13.txt",
            "test/in.3237.public_14.txt",
            "test/in.3237.public_15.txt",
            "test/in.3237.public_16.txt",
            "test/in.3237.public_17.txt",
            "test/in.3237.public_18.txt",
            "test/in.3237.public_19.txt",
            "test/in.3237.public_20.txt",
            "test/in.3237.public_4.txt",
            "test/in.3237.public_5.txt",
            "test/in.3237.public_6.txt",
            "test/in.3237.public_7.txt",
            "test/in.3237.public_8.txt",
            "test/in.3237.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 2,
        "subject": "Lab-10",
        "bug_id": "3238-303624",
        "binary_path": "303624",
        "source_file": "303624_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3238.1.txt",
            "test/in.3238.2.txt",
            "test/in.3238.3.txt",
            "test/in.3238.4.txt",
            "test/in.3238.5.txt",
            "test/in.3238.public_10.txt",
            "test/in.3238.public_11.txt",
            "test/in.3238.public_12.txt",
            "test/in.3238.public_13.txt",
            "test/in.3238.public_14.txt",
            "test/in.3238.public_15.txt",
            "test/in.3238.public_16.txt",
            "test/in.3238.public_17.txt",
            "test/in.3238.public_18.txt",
            "test/in.3238.public_19.txt",
            "test/in.3238.public_20.txt",
            "test/in.3238.public_6.txt",
            "test/in.3238.public_7.txt",
            "test/in.3238.public_8.txt",
            "test/in.3238.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 3,
        "subject": "Lab-10",
        "bug_id": "3238-303722",
        "binary_path": "303722",
        "source_file": "303722_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3238.1.txt",
            "test/in.3238.2.txt",
            "test/in.3238.3.txt",
            "test/in.3238.4.txt",
            "test/in.3238.5.txt",
            "test/in.3238.public_10.txt",
            "test/in.3238.public_11.txt",
            "test/in.3238.public_12.txt",
            "test/in.3238.public_13.txt",
            "test/in.3238.public_14.txt",
            "test/in.3238.public_15.txt",
            "test/in.3238.public_16.txt",
            "test/in.3238.public_17.txt",
            "test/in.3238.public_18.txt",
            "test/in.3238.public_19.txt",
            "test/in.3238.public_20.txt",
            "test/in.3238.public_6.txt",
            "test/in.3238.public_7.txt",
            "test/in.3238.public_8.txt",
            "test/in.3238.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 4,
        "subject": "Lab-10",
        "bug_id": "3239-303888",
        "binary_path": "303888",
        "source_file": "303888_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "public_11",
            "public_12",
            "public_14",
            "public_16",
            "public_18",
            "public_19"
        ],
        "passing_test": [
            "public_10",
            "public_15"
        ],
        "count_neg": 15,
        "count_pos": 2,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3239.1.txt",
            "test/in.3239.2.txt",
            "test/in.3239.3.txt",
            "test/in.3239.4.txt",
            "test/in.3239.5.txt",
            "test/in.3239.6.txt",
            "test/in.3239.7.txt",
            "test/in.3239.8.txt",
            "test/in.3239.9.txt",
            "test/in.3239.public_10.txt",
            "test/in.3239.public_11.txt",
            "test/in.3239.public_12.txt",
            "test/in.3239.public_14.txt",
            "test/in.3239.public_15.txt",
            "test/in.3239.public_16.txt",
            "test/in.3239.public_18.txt",
            "test/in.3239.public_19.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 5,
        "subject": "Lab-10",
        "bug_id": "3239-303919",
        "binary_path": "303919",
        "source_file": "303919_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "2",
            "5",
            "6",
            "public_10",
            "public_11",
            "public_12",
            "public_14",
            "public_15",
            "public_16",
            "public_18",
            "public_19"
        ],
        "passing_test": [
            "1",
            "3",
            "4",
            "7",
            "8",
            "9"
        ],
        "count_neg": 11,
        "count_pos": 6,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3239.1.txt",
            "test/in.3239.2.txt",
            "test/in.3239.3.txt",
            "test/in.3239.4.txt",
            "test/in.3239.5.txt",
            "test/in.3239.6.txt",
            "test/in.3239.7.txt",
            "test/in.3239.8.txt",
            "test/in.3239.9.txt",
            "test/in.3239.public_10.txt",
            "test/in.3239.public_11.txt",
            "test/in.3239.public_12.txt",
            "test/in.3239.public_13.txt",
            "test/in.3239.public_14.txt",
            "test/in.3239.public_15.txt",
            "test/in.3239.public_16.txt",
            "test/in.3239.public_17.txt",
            "test/in.3239.public_18.txt",
            "test/in.3239.public_19.txt",
            "test/in.3239.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 6,
        "subject": "Lab-10",
        "bug_id": "3239-303947",
        "binary_path": "303947",
        "source_file": "303947_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "2",
            "5",
            "6",
            "public_11",
            "public_12",
            "public_14",
            "public_16",
            "public_18",
            "public_19"
        ],
        "passing_test": [
            "1",
            "3",
            "4",
            "7",
            "8",
            "9",
            "public_10",
            "public_15"
        ],
        "count_neg": 9,
        "count_pos": 8,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3239.1.txt",
            "test/in.3239.2.txt",
            "test/in.3239.3.txt",
            "test/in.3239.4.txt",
            "test/in.3239.5.txt",
            "test/in.3239.6.txt",
            "test/in.3239.7.txt",
            "test/in.3239.8.txt",
            "test/in.3239.9.txt",
            "test/in.3239.public_10.txt",
            "test/in.3239.public_11.txt",
            "test/in.3239.public_12.txt",
            "test/in.3239.public_14.txt",
            "test/in.3239.public_15.txt",
            "test/in.3239.public_16.txt",
            "test/in.3239.public_18.txt",
            "test/in.3239.public_19.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 7,
        "subject": "Lab-10",
        "bug_id": "3240-304151",
        "binary_path": "304151",
        "source_file": "304151_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "public_10",
            "public_12",
            "public_15",
            "public_16",
            "public_20"
        ],
        "passing_test": [],
        "count_neg": 13,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3240.1.txt",
            "test/in.3240.2.txt",
            "test/in.3240.3.txt",
            "test/in.3240.4.txt",
            "test/in.3240.5.txt",
            "test/in.3240.6.txt",
            "test/in.3240.7.txt",
            "test/in.3240.8.txt",
            "test/in.3240.public_10.txt",
            "test/in.3240.public_12.txt",
            "test/in.3240.public_15.txt",
            "test/in.3240.public_16.txt",
            "test/in.3240.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 8,
        "subject": "Lab-10",
        "bug_id": "3240-304171",
        "binary_path": "304171",
        "source_file": "304171_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "public_10",
            "public_12",
            "public_15",
            "public_16",
            "public_20"
        ],
        "passing_test": [],
        "count_neg": 13,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3240.1.txt",
            "test/in.3240.2.txt",
            "test/in.3240.3.txt",
            "test/in.3240.4.txt",
            "test/in.3240.5.txt",
            "test/in.3240.6.txt",
            "test/in.3240.7.txt",
            "test/in.3240.8.txt",
            "test/in.3240.public_10.txt",
            "test/in.3240.public_12.txt",
            "test/in.3240.public_15.txt",
            "test/in.3240.public_16.txt",
            "test/in.3240.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 9,
        "subject": "Lab-10",
        "bug_id": "3240-304221",
        "binary_path": "304221",
        "source_file": "304221_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "public_10",
            "public_12",
            "public_15",
            "public_16",
            "public_20"
        ],
        "passing_test": [],
        "count_neg": 13,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3240.1.txt",
            "test/in.3240.2.txt",
            "test/in.3240.3.txt",
            "test/in.3240.4.txt",
            "test/in.3240.5.txt",
            "test/in.3240.6.txt",
            "test/in.3240.7.txt",
            "test/in.3240.8.txt",
            "test/in.3240.public_10.txt",
            "test/in.3240.public_12.txt",
            "test/in.3240.public_15.txt",
            "test/in.3240.public_16.txt",
            "test/in.3240.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 10,
        "subject": "Lab-10",
        "bug_id": "3241-303500",
        "binary_path": "303500",
        "source_file": "303500_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "5",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [
            "3",
            "4"
        ],
        "count_neg": 18,
        "count_pos": 2,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3241.1.txt",
            "test/in.3241.2.txt",
            "test/in.3241.3.txt",
            "test/in.3241.4.txt",
            "test/in.3241.5.txt",
            "test/in.3241.public_10.txt",
            "test/in.3241.public_11.txt",
            "test/in.3241.public_12.txt",
            "test/in.3241.public_13.txt",
            "test/in.3241.public_14.txt",
            "test/in.3241.public_15.txt",
            "test/in.3241.public_16.txt",
            "test/in.3241.public_17.txt",
            "test/in.3241.public_18.txt",
            "test/in.3241.public_19.txt",
            "test/in.3241.public_20.txt",
            "test/in.3241.public_6.txt",
            "test/in.3241.public_7.txt",
            "test/in.3241.public_8.txt",
            "test/in.3241.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 11,
        "subject": "Lab-11",
        "bug_id": "3291-305271",
        "binary_path": "305271",
        "source_file": "305271_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "public_10",
            "public_13",
            "public_14",
            "public_16",
            "public_17",
            "public_19",
            "public_20",
            "public_7",
            "public_9"
        ],
        "passing_test": [
            "public_11",
            "public_12",
            "public_15",
            "public_18",
            "public_8"
        ],
        "count_neg": 15,
        "count_pos": 5,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3291.1.txt",
            "test/in.3291.2.txt",
            "test/in.3291.3.txt",
            "test/in.3291.4.txt",
            "test/in.3291.5.txt",
            "test/in.3291.6.txt",
            "test/in.3291.public_10.txt",
            "test/in.3291.public_11.txt",
            "test/in.3291.public_12.txt",
            "test/in.3291.public_13.txt",
            "test/in.3291.public_14.txt",
            "test/in.3291.public_15.txt",
            "test/in.3291.public_16.txt",
            "test/in.3291.public_17.txt",
            "test/in.3291.public_18.txt",
            "test/in.3291.public_19.txt",
            "test/in.3291.public_20.txt",
            "test/in.3291.public_7.txt",
            "test/in.3291.public_8.txt",
            "test/in.3291.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 12,
        "subject": "Lab-11",
        "bug_id": "3291-305284",
        "binary_path": "305284",
        "source_file": "305284_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3291.1.txt",
            "test/in.3291.2.txt",
            "test/in.3291.3.txt",
            "test/in.3291.4.txt",
            "test/in.3291.5.txt",
            "test/in.3291.6.txt",
            "test/in.3291.public_10.txt",
            "test/in.3291.public_11.txt",
            "test/in.3291.public_12.txt",
            "test/in.3291.public_13.txt",
            "test/in.3291.public_14.txt",
            "test/in.3291.public_15.txt",
            "test/in.3291.public_16.txt",
            "test/in.3291.public_17.txt",
            "test/in.3291.public_18.txt",
            "test/in.3291.public_19.txt",
            "test/in.3291.public_20.txt",
            "test/in.3291.public_7.txt",
            "test/in.3291.public_8.txt",
            "test/in.3291.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 13,
        "subject": "Lab-11",
        "bug_id": "3293-305756",
        "binary_path": "305756",
        "source_file": "305756_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3293.1.txt",
            "test/in.3293.2.txt",
            "test/in.3293.3.txt",
            "test/in.3293.4.txt",
            "test/in.3293.5.txt",
            "test/in.3293.6.txt",
            "test/in.3293.public_10.txt",
            "test/in.3293.public_11.txt",
            "test/in.3293.public_12.txt",
            "test/in.3293.public_13.txt",
            "test/in.3293.public_14.txt",
            "test/in.3293.public_15.txt",
            "test/in.3293.public_16.txt",
            "test/in.3293.public_17.txt",
            "test/in.3293.public_18.txt",
            "test/in.3293.public_19.txt",
            "test/in.3293.public_20.txt",
            "test/in.3293.public_7.txt",
            "test/in.3293.public_8.txt",
            "test/in.3293.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 14,
        "subject": "Lab-11",
        "bug_id": "3293-305783",
        "binary_path": "305783",
        "source_file": "305783_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3293.1.txt",
            "test/in.3293.2.txt",
            "test/in.3293.3.txt",
            "test/in.3293.4.txt",
            "test/in.3293.5.txt",
            "test/in.3293.6.txt",
            "test/in.3293.public_10.txt",
            "test/in.3293.public_11.txt",
            "test/in.3293.public_12.txt",
            "test/in.3293.public_13.txt",
            "test/in.3293.public_14.txt",
            "test/in.3293.public_15.txt",
            "test/in.3293.public_16.txt",
            "test/in.3293.public_17.txt",
            "test/in.3293.public_18.txt",
            "test/in.3293.public_19.txt",
            "test/in.3293.public_20.txt",
            "test/in.3293.public_7.txt",
            "test/in.3293.public_8.txt",
            "test/in.3293.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 15,
        "subject": "Lab-11",
        "bug_id": "3294-305975",
        "binary_path": "305975",
        "source_file": "305975_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_12",
            "public_14",
            "public_17",
            "public_20",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 13,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3294.1.txt",
            "test/in.3294.2.txt",
            "test/in.3294.3.txt",
            "test/in.3294.4.txt",
            "test/in.3294.5.txt",
            "test/in.3294.public_10.txt",
            "test/in.3294.public_11.txt",
            "test/in.3294.public_12.txt",
            "test/in.3294.public_13.txt",
            "test/in.3294.public_14.txt",
            "test/in.3294.public_15.txt",
            "test/in.3294.public_16.txt",
            "test/in.3294.public_17.txt",
            "test/in.3294.public_18.txt",
            "test/in.3294.public_19.txt",
            "test/in.3294.public_20.txt",
            "test/in.3294.public_6.txt",
            "test/in.3294.public_7.txt",
            "test/in.3294.public_8.txt",
            "test/in.3294.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 16,
        "subject": "Lab-11",
        "bug_id": "3294-305984",
        "binary_path": "305984",
        "source_file": "305984_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_12",
            "public_14",
            "public_17",
            "public_20",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 13,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3294.1.txt",
            "test/in.3294.2.txt",
            "test/in.3294.3.txt",
            "test/in.3294.4.txt",
            "test/in.3294.5.txt",
            "test/in.3294.public_10.txt",
            "test/in.3294.public_11.txt",
            "test/in.3294.public_12.txt",
            "test/in.3294.public_13.txt",
            "test/in.3294.public_14.txt",
            "test/in.3294.public_15.txt",
            "test/in.3294.public_16.txt",
            "test/in.3294.public_17.txt",
            "test/in.3294.public_18.txt",
            "test/in.3294.public_19.txt",
            "test/in.3294.public_20.txt",
            "test/in.3294.public_6.txt",
            "test/in.3294.public_7.txt",
            "test/in.3294.public_8.txt",
            "test/in.3294.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 17,
        "subject": "Lab-11",
        "bug_id": "3294-305996",
        "binary_path": "305996",
        "source_file": "305996_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_14",
            "public_17",
            "public_20",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [
            "public_12"
        ],
        "count_neg": 12,
        "count_pos": 1,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3294.1.txt",
            "test/in.3294.2.txt",
            "test/in.3294.3.txt",
            "test/in.3294.4.txt",
            "test/in.3294.5.txt",
            "test/in.3294.public_10.txt",
            "test/in.3294.public_12.txt",
            "test/in.3294.public_13.txt",
            "test/in.3294.public_14.txt",
            "test/in.3294.public_15.txt",
            "test/in.3294.public_16.txt",
            "test/in.3294.public_17.txt",
            "test/in.3294.public_18.txt",
            "test/in.3294.public_19.txt",
            "test/in.3294.public_20.txt",
            "test/in.3294.public_6.txt",
            "test/in.3294.public_7.txt",
            "test/in.3294.public_8.txt",
            "test/in.3294.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 18,
        "subject": "Lab-11",
        "bug_id": "3294-306033",
        "binary_path": "306033",
        "source_file": "306033_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_12",
            "public_14",
            "public_17",
            "public_20",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 13,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3294.1.txt",
            "test/in.3294.2.txt",
            "test/in.3294.3.txt",
            "test/in.3294.4.txt",
            "test/in.3294.5.txt",
            "test/in.3294.public_10.txt",
            "test/in.3294.public_11.txt",
            "test/in.3294.public_12.txt",
            "test/in.3294.public_13.txt",
            "test/in.3294.public_14.txt",
            "test/in.3294.public_15.txt",
            "test/in.3294.public_16.txt",
            "test/in.3294.public_17.txt",
            "test/in.3294.public_18.txt",
            "test/in.3294.public_19.txt",
            "test/in.3294.public_20.txt",
            "test/in.3294.public_6.txt",
            "test/in.3294.public_7.txt",
            "test/in.3294.public_8.txt",
            "test/in.3294.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 19,
        "subject": "Lab-11",
        "bug_id": "3294-306056",
        "binary_path": "306056",
        "source_file": "306056_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_12",
            "public_14",
            "public_17",
            "public_20",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 13,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3294.1.txt",
            "test/in.3294.2.txt",
            "test/in.3294.3.txt",
            "test/in.3294.4.txt",
            "test/in.3294.5.txt",
            "test/in.3294.public_10.txt",
            "test/in.3294.public_11.txt",
            "test/in.3294.public_12.txt",
            "test/in.3294.public_13.txt",
            "test/in.3294.public_14.txt",
            "test/in.3294.public_15.txt",
            "test/in.3294.public_16.txt",
            "test/in.3294.public_17.txt",
            "test/in.3294.public_18.txt",
            "test/in.3294.public_19.txt",
            "test/in.3294.public_20.txt",
            "test/in.3294.public_6.txt",
            "test/in.3294.public_7.txt",
            "test/in.3294.public_8.txt",
            "test/in.3294.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 20,
        "subject": "Lab-11",
        "bug_id": "3295-305374",
        "binary_path": "305374",
        "source_file": "305374_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_19",
            "public_20",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 19,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3295.1.txt",
            "test/in.3295.2.txt",
            "test/in.3295.3.txt",
            "test/in.3295.4.txt",
            "test/in.3295.5.txt",
            "test/in.3295.6.txt",
            "test/in.3295.7.txt",
            "test/in.3295.public_10.txt",
            "test/in.3295.public_11.txt",
            "test/in.3295.public_12.txt",
            "test/in.3295.public_13.txt",
            "test/in.3295.public_14.txt",
            "test/in.3295.public_15.txt",
            "test/in.3295.public_16.txt",
            "test/in.3295.public_17.txt",
            "test/in.3295.public_19.txt",
            "test/in.3295.public_20.txt",
            "test/in.3295.public_8.txt",
            "test/in.3295.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 21,
        "subject": "Lab-12",
        "bug_id": "3355-307020",
        "binary_path": "307020",
        "source_file": "307020_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3355.1.txt",
            "test/in.3355.2.txt",
            "test/in.3355.3.txt",
            "test/in.3355.4.txt",
            "test/in.3355.5.txt",
            "test/in.3355.6.txt",
            "test/in.3355.7.txt",
            "test/in.3355.8.txt",
            "test/in.3355.9.txt",
            "test/in.3355.public_10.txt",
            "test/in.3355.public_11.txt",
            "test/in.3355.public_12.txt",
            "test/in.3355.public_13.txt",
            "test/in.3355.public_14.txt",
            "test/in.3355.public_15.txt",
            "test/in.3355.public_16.txt",
            "test/in.3355.public_17.txt",
            "test/in.3355.public_18.txt",
            "test/in.3355.public_19.txt",
            "test/in.3355.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 22,
        "subject": "Lab-12",
        "bug_id": "3355-307064",
        "binary_path": "307064",
        "source_file": "307064_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3355.1.txt",
            "test/in.3355.2.txt",
            "test/in.3355.3.txt",
            "test/in.3355.4.txt",
            "test/in.3355.5.txt",
            "test/in.3355.6.txt",
            "test/in.3355.7.txt",
            "test/in.3355.8.txt",
            "test/in.3355.9.txt",
            "test/in.3355.public_10.txt",
            "test/in.3355.public_11.txt",
            "test/in.3355.public_12.txt",
            "test/in.3355.public_13.txt",
            "test/in.3355.public_14.txt",
            "test/in.3355.public_15.txt",
            "test/in.3355.public_16.txt",
            "test/in.3355.public_17.txt",
            "test/in.3355.public_18.txt",
            "test/in.3355.public_19.txt",
            "test/in.3355.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 23,
        "subject": "Lab-12",
        "bug_id": "3355-307083",
        "binary_path": "307083",
        "source_file": "307083_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3355.1.txt",
            "test/in.3355.2.txt",
            "test/in.3355.3.txt",
            "test/in.3355.4.txt",
            "test/in.3355.5.txt",
            "test/in.3355.6.txt",
            "test/in.3355.7.txt",
            "test/in.3355.8.txt",
            "test/in.3355.9.txt",
            "test/in.3355.public_10.txt",
            "test/in.3355.public_11.txt",
            "test/in.3355.public_12.txt",
            "test/in.3355.public_13.txt",
            "test/in.3355.public_14.txt",
            "test/in.3355.public_15.txt",
            "test/in.3355.public_16.txt",
            "test/in.3355.public_17.txt",
            "test/in.3355.public_18.txt",
            "test/in.3355.public_19.txt",
            "test/in.3355.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 24,
        "subject": "Lab-12",
        "bug_id": "3355-307102",
        "binary_path": "307102",
        "source_file": "307102_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3355.1.txt",
            "test/in.3355.2.txt",
            "test/in.3355.3.txt",
            "test/in.3355.4.txt",
            "test/in.3355.5.txt",
            "test/in.3355.6.txt",
            "test/in.3355.7.txt",
            "test/in.3355.8.txt",
            "test/in.3355.9.txt",
            "test/in.3355.public_10.txt",
            "test/in.3355.public_11.txt",
            "test/in.3355.public_12.txt",
            "test/in.3355.public_13.txt",
            "test/in.3355.public_14.txt",
            "test/in.3355.public_15.txt",
            "test/in.3355.public_16.txt",
            "test/in.3355.public_17.txt",
            "test/in.3355.public_18.txt",
            "test/in.3355.public_19.txt",
            "test/in.3355.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 25,
        "subject": "Lab-12",
        "bug_id": "3356-307281",
        "binary_path": "307281",
        "source_file": "307281_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3356.1.txt",
            "test/in.3356.2.txt",
            "test/in.3356.3.txt",
            "test/in.3356.4.txt",
            "test/in.3356.5.txt",
            "test/in.3356.6.txt",
            "test/in.3356.7.txt",
            "test/in.3356.public_10.txt",
            "test/in.3356.public_11.txt",
            "test/in.3356.public_12.txt",
            "test/in.3356.public_13.txt",
            "test/in.3356.public_14.txt",
            "test/in.3356.public_15.txt",
            "test/in.3356.public_16.txt",
            "test/in.3356.public_17.txt",
            "test/in.3356.public_18.txt",
            "test/in.3356.public_19.txt",
            "test/in.3356.public_20.txt",
            "test/in.3356.public_8.txt",
            "test/in.3356.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 26,
        "subject": "Lab-12",
        "bug_id": "3356-307320",
        "binary_path": "307320",
        "source_file": "307320_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3356.1.txt",
            "test/in.3356.2.txt",
            "test/in.3356.3.txt",
            "test/in.3356.4.txt",
            "test/in.3356.5.txt",
            "test/in.3356.6.txt",
            "test/in.3356.7.txt",
            "test/in.3356.public_10.txt",
            "test/in.3356.public_11.txt",
            "test/in.3356.public_12.txt",
            "test/in.3356.public_13.txt",
            "test/in.3356.public_14.txt",
            "test/in.3356.public_15.txt",
            "test/in.3356.public_16.txt",
            "test/in.3356.public_17.txt",
            "test/in.3356.public_18.txt",
            "test/in.3356.public_19.txt",
            "test/in.3356.public_20.txt",
            "test/in.3356.public_8.txt",
            "test/in.3356.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 27,
        "subject": "Lab-12",
        "bug_id": "3356-307361",
        "binary_path": "307361",
        "source_file": "307361_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "4",
            "7",
            "public_10",
            "public_13",
            "public_14",
            "public_19",
            "public_20",
            "public_8"
        ],
        "passing_test": [
            "3",
            "5",
            "6",
            "public_11",
            "public_12",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_9"
        ],
        "count_neg": 10,
        "count_pos": 10,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3356.1.txt",
            "test/in.3356.2.txt",
            "test/in.3356.3.txt",
            "test/in.3356.4.txt",
            "test/in.3356.5.txt",
            "test/in.3356.6.txt",
            "test/in.3356.7.txt",
            "test/in.3356.public_10.txt",
            "test/in.3356.public_11.txt",
            "test/in.3356.public_12.txt",
            "test/in.3356.public_13.txt",
            "test/in.3356.public_14.txt",
            "test/in.3356.public_15.txt",
            "test/in.3356.public_16.txt",
            "test/in.3356.public_17.txt",
            "test/in.3356.public_18.txt",
            "test/in.3356.public_19.txt",
            "test/in.3356.public_20.txt",
            "test/in.3356.public_8.txt",
            "test/in.3356.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 28,
        "subject": "Lab-12",
        "bug_id": "3357-307516",
        "binary_path": "307516",
        "source_file": "307516_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "2",
            "4",
            "6",
            "public_12",
            "public_8"
        ],
        "passing_test": [
            "1",
            "3",
            "5",
            "7",
            "public_10",
            "public_11",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_9"
        ],
        "count_neg": 5,
        "count_pos": 15,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3357.1.txt",
            "test/in.3357.2.txt",
            "test/in.3357.3.txt",
            "test/in.3357.4.txt",
            "test/in.3357.5.txt",
            "test/in.3357.6.txt",
            "test/in.3357.7.txt",
            "test/in.3357.public_10.txt",
            "test/in.3357.public_11.txt",
            "test/in.3357.public_12.txt",
            "test/in.3357.public_13.txt",
            "test/in.3357.public_14.txt",
            "test/in.3357.public_15.txt",
            "test/in.3357.public_16.txt",
            "test/in.3357.public_17.txt",
            "test/in.3357.public_18.txt",
            "test/in.3357.public_19.txt",
            "test/in.3357.public_20.txt",
            "test/in.3357.public_8.txt",
            "test/in.3357.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 29,
        "subject": "Lab-12",
        "bug_id": "3357-307562",
        "binary_path": "307562",
        "source_file": "307562_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3357.1.txt",
            "test/in.3357.2.txt",
            "test/in.3357.3.txt",
            "test/in.3357.4.txt",
            "test/in.3357.5.txt",
            "test/in.3357.6.txt",
            "test/in.3357.7.txt",
            "test/in.3357.public_10.txt",
            "test/in.3357.public_11.txt",
            "test/in.3357.public_12.txt",
            "test/in.3357.public_13.txt",
            "test/in.3357.public_14.txt",
            "test/in.3357.public_15.txt",
            "test/in.3357.public_16.txt",
            "test/in.3357.public_17.txt",
            "test/in.3357.public_18.txt",
            "test/in.3357.public_19.txt",
            "test/in.3357.public_20.txt",
            "test/in.3357.public_8.txt",
            "test/in.3357.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 30,
        "subject": "Lab-12",
        "bug_id": "3358-307777",
        "binary_path": "307777",
        "source_file": "307777_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3358.1.txt",
            "test/in.3358.2.txt",
            "test/in.3358.3.txt",
            "test/in.3358.4.txt",
            "test/in.3358.5.txt",
            "test/in.3358.6.txt",
            "test/in.3358.7.txt",
            "test/in.3358.public_10.txt",
            "test/in.3358.public_11.txt",
            "test/in.3358.public_12.txt",
            "test/in.3358.public_13.txt",
            "test/in.3358.public_14.txt",
            "test/in.3358.public_15.txt",
            "test/in.3358.public_16.txt",
            "test/in.3358.public_17.txt",
            "test/in.3358.public_18.txt",
            "test/in.3358.public_19.txt",
            "test/in.3358.public_20.txt",
            "test/in.3358.public_8.txt",
            "test/in.3358.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 31,
        "subject": "Lab-3",
        "bug_id": "2810-270011",
        "binary_path": "270011",
        "source_file": "270011_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_5",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 19,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2810.1.txt",
            "test/in.2810.2.txt",
            "test/in.2810.3.txt",
            "test/in.2810.4.txt",
            "test/in.2810.public_10.txt",
            "test/in.2810.public_11.txt",
            "test/in.2810.public_12.txt",
            "test/in.2810.public_13.txt",
            "test/in.2810.public_15.txt",
            "test/in.2810.public_16.txt",
            "test/in.2810.public_17.txt",
            "test/in.2810.public_18.txt",
            "test/in.2810.public_19.txt",
            "test/in.2810.public_20.txt",
            "test/in.2810.public_5.txt",
            "test/in.2810.public_6.txt",
            "test/in.2810.public_7.txt",
            "test/in.2810.public_8.txt",
            "test/in.2810.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 32,
        "subject": "Lab-3",
        "bug_id": "2810-270048",
        "binary_path": "270048",
        "source_file": "270048_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_5",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 19,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2810.1.txt",
            "test/in.2810.2.txt",
            "test/in.2810.3.txt",
            "test/in.2810.4.txt",
            "test/in.2810.public_10.txt",
            "test/in.2810.public_11.txt",
            "test/in.2810.public_12.txt",
            "test/in.2810.public_13.txt",
            "test/in.2810.public_15.txt",
            "test/in.2810.public_16.txt",
            "test/in.2810.public_17.txt",
            "test/in.2810.public_18.txt",
            "test/in.2810.public_19.txt",
            "test/in.2810.public_20.txt",
            "test/in.2810.public_5.txt",
            "test/in.2810.public_6.txt",
            "test/in.2810.public_7.txt",
            "test/in.2810.public_8.txt",
            "test/in.2810.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 33,
        "subject": "Lab-3",
        "bug_id": "2810-270054",
        "binary_path": "270054",
        "source_file": "270054_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_5",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 19,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2810.1.txt",
            "test/in.2810.2.txt",
            "test/in.2810.3.txt",
            "test/in.2810.4.txt",
            "test/in.2810.public_10.txt",
            "test/in.2810.public_11.txt",
            "test/in.2810.public_12.txt",
            "test/in.2810.public_13.txt",
            "test/in.2810.public_15.txt",
            "test/in.2810.public_16.txt",
            "test/in.2810.public_17.txt",
            "test/in.2810.public_18.txt",
            "test/in.2810.public_19.txt",
            "test/in.2810.public_20.txt",
            "test/in.2810.public_5.txt",
            "test/in.2810.public_6.txt",
            "test/in.2810.public_7.txt",
            "test/in.2810.public_8.txt",
            "test/in.2810.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 34,
        "subject": "Lab-3",
        "bug_id": "2810-270081",
        "binary_path": "270081",
        "source_file": "270081_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_5",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 19,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2810.1.txt",
            "test/in.2810.2.txt",
            "test/in.2810.3.txt",
            "test/in.2810.4.txt",
            "test/in.2810.public_10.txt",
            "test/in.2810.public_11.txt",
            "test/in.2810.public_12.txt",
            "test/in.2810.public_13.txt",
            "test/in.2810.public_15.txt",
            "test/in.2810.public_16.txt",
            "test/in.2810.public_17.txt",
            "test/in.2810.public_18.txt",
            "test/in.2810.public_19.txt",
            "test/in.2810.public_20.txt",
            "test/in.2810.public_5.txt",
            "test/in.2810.public_6.txt",
            "test/in.2810.public_7.txt",
            "test/in.2810.public_8.txt",
            "test/in.2810.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 35,
        "subject": "Lab-3",
        "bug_id": "2810-270090",
        "binary_path": "270090",
        "source_file": "270090_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_5",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 19,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2810.1.txt",
            "test/in.2810.2.txt",
            "test/in.2810.3.txt",
            "test/in.2810.4.txt",
            "test/in.2810.public_10.txt",
            "test/in.2810.public_11.txt",
            "test/in.2810.public_12.txt",
            "test/in.2810.public_13.txt",
            "test/in.2810.public_15.txt",
            "test/in.2810.public_16.txt",
            "test/in.2810.public_17.txt",
            "test/in.2810.public_18.txt",
            "test/in.2810.public_19.txt",
            "test/in.2810.public_20.txt",
            "test/in.2810.public_5.txt",
            "test/in.2810.public_6.txt",
            "test/in.2810.public_7.txt",
            "test/in.2810.public_8.txt",
            "test/in.2810.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 36,
        "subject": "Lab-3",
        "bug_id": "2811-270138",
        "binary_path": "270138",
        "source_file": "270138_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_20",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 19,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2811.1.txt",
            "test/in.2811.2.txt",
            "test/in.2811.3.txt",
            "test/in.2811.4.txt",
            "test/in.2811.5.txt",
            "test/in.2811.6.txt",
            "test/in.2811.public_10.txt",
            "test/in.2811.public_11.txt",
            "test/in.2811.public_12.txt",
            "test/in.2811.public_13.txt",
            "test/in.2811.public_14.txt",
            "test/in.2811.public_15.txt",
            "test/in.2811.public_16.txt",
            "test/in.2811.public_17.txt",
            "test/in.2811.public_18.txt",
            "test/in.2811.public_20.txt",
            "test/in.2811.public_8.txt",
            "test/in.2811.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 37,
        "subject": "Lab-3",
        "bug_id": "2811-270151",
        "binary_path": "270151",
        "source_file": "270151_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "4",
            "6",
            "public_15",
            "public_8"
        ],
        "passing_test": [
            "1",
            "2",
            "3",
            "5",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_16",
            "public_17",
            "public_18",
            "public_20",
            "public_9"
        ],
        "count_neg": 4,
        "count_pos": 15,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2811.1.txt",
            "test/in.2811.2.txt",
            "test/in.2811.3.txt",
            "test/in.2811.4.txt",
            "test/in.2811.5.txt",
            "test/in.2811.6.txt",
            "test/in.2811.public_10.txt",
            "test/in.2811.public_11.txt",
            "test/in.2811.public_12.txt",
            "test/in.2811.public_13.txt",
            "test/in.2811.public_14.txt",
            "test/in.2811.public_15.txt",
            "test/in.2811.public_16.txt",
            "test/in.2811.public_17.txt",
            "test/in.2811.public_18.txt",
            "test/in.2811.public_20.txt",
            "test/in.2811.public_8.txt",
            "test/in.2811.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 38,
        "subject": "Lab-3",
        "bug_id": "2811-270194",
        "binary_path": "270194",
        "source_file": "270194_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "3",
            "4",
            "6",
            "public_10",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_20",
            "public_8",
            "public_9"
        ],
        "passing_test": [
            "2",
            "5",
            "public_11",
            "public_12",
            "public_18"
        ],
        "count_neg": 13,
        "count_pos": 6,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2811.1.txt",
            "test/in.2811.2.txt",
            "test/in.2811.3.txt",
            "test/in.2811.4.txt",
            "test/in.2811.5.txt",
            "test/in.2811.6.txt",
            "test/in.2811.public_10.txt",
            "test/in.2811.public_11.txt",
            "test/in.2811.public_12.txt",
            "test/in.2811.public_13.txt",
            "test/in.2811.public_14.txt",
            "test/in.2811.public_15.txt",
            "test/in.2811.public_16.txt",
            "test/in.2811.public_17.txt",
            "test/in.2811.public_18.txt",
            "test/in.2811.public_20.txt",
            "test/in.2811.public_8.txt",
            "test/in.2811.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 39,
        "subject": "Lab-3",
        "bug_id": "2811-270220",
        "binary_path": "270220",
        "source_file": "270220_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_20",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 19,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2811.1.txt",
            "test/in.2811.2.txt",
            "test/in.2811.3.txt",
            "test/in.2811.4.txt",
            "test/in.2811.5.txt",
            "test/in.2811.6.txt",
            "test/in.2811.public_10.txt",
            "test/in.2811.public_11.txt",
            "test/in.2811.public_12.txt",
            "test/in.2811.public_13.txt",
            "test/in.2811.public_14.txt",
            "test/in.2811.public_15.txt",
            "test/in.2811.public_16.txt",
            "test/in.2811.public_17.txt",
            "test/in.2811.public_18.txt",
            "test/in.2811.public_20.txt",
            "test/in.2811.public_8.txt",
            "test/in.2811.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 40,
        "subject": "Lab-3",
        "bug_id": "2812-270276",
        "binary_path": "270276",
        "source_file": "270276_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "3",
            "6",
            "public_15"
        ],
        "passing_test": [
            "1",
            "2",
            "4",
            "5",
            "7",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_8",
            "public_9"
        ],
        "count_neg": 3,
        "count_pos": 17,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2812.1.txt",
            "test/in.2812.2.txt",
            "test/in.2812.3.txt",
            "test/in.2812.4.txt",
            "test/in.2812.5.txt",
            "test/in.2812.6.txt",
            "test/in.2812.7.txt",
            "test/in.2812.public_10.txt",
            "test/in.2812.public_11.txt",
            "test/in.2812.public_12.txt",
            "test/in.2812.public_13.txt",
            "test/in.2812.public_14.txt",
            "test/in.2812.public_15.txt",
            "test/in.2812.public_16.txt",
            "test/in.2812.public_17.txt",
            "test/in.2812.public_18.txt",
            "test/in.2812.public_19.txt",
            "test/in.2812.public_20.txt",
            "test/in.2812.public_8.txt",
            "test/in.2812.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 41,
        "subject": "Lab-4",
        "bug_id": "2824-271039",
        "binary_path": "271039",
        "source_file": "271039_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "5",
            "6",
            "7"
        ],
        "passing_test": [
            "1",
            "2",
            "3",
            "4",
            "8",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_9"
        ],
        "count_neg": 3,
        "count_pos": 17,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2824.1.txt",
            "test/in.2824.2.txt",
            "test/in.2824.3.txt",
            "test/in.2824.4.txt",
            "test/in.2824.5.txt",
            "test/in.2824.6.txt",
            "test/in.2824.7.txt",
            "test/in.2824.8.txt",
            "test/in.2824.public_10.txt",
            "test/in.2824.public_11.txt",
            "test/in.2824.public_12.txt",
            "test/in.2824.public_13.txt",
            "test/in.2824.public_14.txt",
            "test/in.2824.public_15.txt",
            "test/in.2824.public_16.txt",
            "test/in.2824.public_17.txt",
            "test/in.2824.public_18.txt",
            "test/in.2824.public_19.txt",
            "test/in.2824.public_20.txt",
            "test/in.2824.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 42,
        "subject": "Lab-4",
        "bug_id": "2824-271080",
        "binary_path": "271080",
        "source_file": "271080_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "5",
            "6",
            "7"
        ],
        "passing_test": [
            "1",
            "2",
            "3",
            "4",
            "8",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_9"
        ],
        "count_neg": 3,
        "count_pos": 17,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2824.1.txt",
            "test/in.2824.2.txt",
            "test/in.2824.3.txt",
            "test/in.2824.4.txt",
            "test/in.2824.5.txt",
            "test/in.2824.6.txt",
            "test/in.2824.7.txt",
            "test/in.2824.8.txt",
            "test/in.2824.public_10.txt",
            "test/in.2824.public_11.txt",
            "test/in.2824.public_12.txt",
            "test/in.2824.public_13.txt",
            "test/in.2824.public_14.txt",
            "test/in.2824.public_15.txt",
            "test/in.2824.public_16.txt",
            "test/in.2824.public_17.txt",
            "test/in.2824.public_18.txt",
            "test/in.2824.public_19.txt",
            "test/in.2824.public_20.txt",
            "test/in.2824.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 43,
        "subject": "Lab-4",
        "bug_id": "2824-271084",
        "binary_path": "271084",
        "source_file": "271084_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "3",
            "public_10",
            "public_15",
            "public_19"
        ],
        "passing_test": [
            "2",
            "4",
            "5",
            "6",
            "7",
            "8",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_16",
            "public_17",
            "public_18",
            "public_20",
            "public_9"
        ],
        "count_neg": 5,
        "count_pos": 15,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2824.1.txt",
            "test/in.2824.2.txt",
            "test/in.2824.3.txt",
            "test/in.2824.4.txt",
            "test/in.2824.5.txt",
            "test/in.2824.6.txt",
            "test/in.2824.7.txt",
            "test/in.2824.8.txt",
            "test/in.2824.public_10.txt",
            "test/in.2824.public_11.txt",
            "test/in.2824.public_12.txt",
            "test/in.2824.public_13.txt",
            "test/in.2824.public_14.txt",
            "test/in.2824.public_15.txt",
            "test/in.2824.public_16.txt",
            "test/in.2824.public_17.txt",
            "test/in.2824.public_18.txt",
            "test/in.2824.public_19.txt",
            "test/in.2824.public_20.txt",
            "test/in.2824.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 44,
        "subject": "Lab-4",
        "bug_id": "2824-271095",
        "binary_path": "271095",
        "source_file": "271095_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "3",
            "8",
            "public_10",
            "public_15",
            "public_19"
        ],
        "passing_test": [
            "2",
            "4",
            "5",
            "6",
            "7",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_16",
            "public_17",
            "public_18",
            "public_20",
            "public_9"
        ],
        "count_neg": 6,
        "count_pos": 14,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2824.1.txt",
            "test/in.2824.2.txt",
            "test/in.2824.3.txt",
            "test/in.2824.4.txt",
            "test/in.2824.5.txt",
            "test/in.2824.6.txt",
            "test/in.2824.7.txt",
            "test/in.2824.8.txt",
            "test/in.2824.public_10.txt",
            "test/in.2824.public_11.txt",
            "test/in.2824.public_12.txt",
            "test/in.2824.public_13.txt",
            "test/in.2824.public_14.txt",
            "test/in.2824.public_15.txt",
            "test/in.2824.public_16.txt",
            "test/in.2824.public_17.txt",
            "test/in.2824.public_18.txt",
            "test/in.2824.public_19.txt",
            "test/in.2824.public_20.txt",
            "test/in.2824.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 45,
        "subject": "Lab-4",
        "bug_id": "2824-271116",
        "binary_path": "271116",
        "source_file": "271116_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "2",
            "4",
            "5",
            "6",
            "7",
            "8",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_16",
            "public_17",
            "public_18",
            "public_20",
            "public_9"
        ],
        "passing_test": [
            "1",
            "3",
            "public_10",
            "public_15",
            "public_19"
        ],
        "count_neg": 15,
        "count_pos": 5,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2824.1.txt",
            "test/in.2824.2.txt",
            "test/in.2824.3.txt",
            "test/in.2824.4.txt",
            "test/in.2824.5.txt",
            "test/in.2824.6.txt",
            "test/in.2824.7.txt",
            "test/in.2824.8.txt",
            "test/in.2824.public_10.txt",
            "test/in.2824.public_11.txt",
            "test/in.2824.public_12.txt",
            "test/in.2824.public_13.txt",
            "test/in.2824.public_14.txt",
            "test/in.2824.public_15.txt",
            "test/in.2824.public_16.txt",
            "test/in.2824.public_17.txt",
            "test/in.2824.public_18.txt",
            "test/in.2824.public_19.txt",
            "test/in.2824.public_20.txt",
            "test/in.2824.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 46,
        "subject": "Lab-4",
        "bug_id": "2825-271154",
        "binary_path": "271154",
        "source_file": "271154_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2825.1.txt",
            "test/in.2825.2.txt",
            "test/in.2825.3.txt",
            "test/in.2825.4.txt",
            "test/in.2825.5.txt",
            "test/in.2825.6.txt",
            "test/in.2825.7.txt",
            "test/in.2825.public_10.txt",
            "test/in.2825.public_11.txt",
            "test/in.2825.public_12.txt",
            "test/in.2825.public_13.txt",
            "test/in.2825.public_14.txt",
            "test/in.2825.public_15.txt",
            "test/in.2825.public_16.txt",
            "test/in.2825.public_17.txt",
            "test/in.2825.public_18.txt",
            "test/in.2825.public_19.txt",
            "test/in.2825.public_8.txt",
            "test/in.2825.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 47,
        "subject": "Lab-4",
        "bug_id": "2825-271188",
        "binary_path": "271188",
        "source_file": "271188_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "6",
            "7",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_8",
            "public_9"
        ],
        "passing_test": [
            "4",
            "5",
            "public_10"
        ],
        "count_neg": 17,
        "count_pos": 3,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2825.1.txt",
            "test/in.2825.2.txt",
            "test/in.2825.3.txt",
            "test/in.2825.4.txt",
            "test/in.2825.5.txt",
            "test/in.2825.6.txt",
            "test/in.2825.7.txt",
            "test/in.2825.public_10.txt",
            "test/in.2825.public_11.txt",
            "test/in.2825.public_12.txt",
            "test/in.2825.public_13.txt",
            "test/in.2825.public_14.txt",
            "test/in.2825.public_15.txt",
            "test/in.2825.public_16.txt",
            "test/in.2825.public_17.txt",
            "test/in.2825.public_18.txt",
            "test/in.2825.public_19.txt",
            "test/in.2825.public_8.txt",
            "test/in.2825.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 48,
        "subject": "Lab-4",
        "bug_id": "2825-271203",
        "binary_path": "271203",
        "source_file": "271203_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "6",
            "7",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_8",
            "public_9"
        ],
        "passing_test": [
            "4",
            "5",
            "public_10"
        ],
        "count_neg": 17,
        "count_pos": 3,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2825.1.txt",
            "test/in.2825.2.txt",
            "test/in.2825.3.txt",
            "test/in.2825.4.txt",
            "test/in.2825.5.txt",
            "test/in.2825.6.txt",
            "test/in.2825.7.txt",
            "test/in.2825.public_10.txt",
            "test/in.2825.public_11.txt",
            "test/in.2825.public_12.txt",
            "test/in.2825.public_13.txt",
            "test/in.2825.public_14.txt",
            "test/in.2825.public_15.txt",
            "test/in.2825.public_16.txt",
            "test/in.2825.public_17.txt",
            "test/in.2825.public_18.txt",
            "test/in.2825.public_19.txt",
            "test/in.2825.public_8.txt",
            "test/in.2825.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 49,
        "subject": "Lab-4",
        "bug_id": "2825-271209",
        "binary_path": "271209",
        "source_file": "271209_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2825.1.txt",
            "test/in.2825.2.txt",
            "test/in.2825.3.txt",
            "test/in.2825.4.txt",
            "test/in.2825.5.txt",
            "test/in.2825.6.txt",
            "test/in.2825.7.txt",
            "test/in.2825.public_10.txt",
            "test/in.2825.public_11.txt",
            "test/in.2825.public_12.txt",
            "test/in.2825.public_13.txt",
            "test/in.2825.public_14.txt",
            "test/in.2825.public_15.txt",
            "test/in.2825.public_16.txt",
            "test/in.2825.public_17.txt",
            "test/in.2825.public_18.txt",
            "test/in.2825.public_19.txt",
            "test/in.2825.public_8.txt",
            "test/in.2825.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 50,
        "subject": "Lab-4",
        "bug_id": "2825-271216",
        "binary_path": "271216",
        "source_file": "271216_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "3",
            "6",
            "public_11"
        ],
        "passing_test": [
            "1",
            "2",
            "4",
            "5",
            "7",
            "public_10",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_8",
            "public_9"
        ],
        "count_neg": 3,
        "count_pos": 17,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2825.1.txt",
            "test/in.2825.2.txt",
            "test/in.2825.3.txt",
            "test/in.2825.4.txt",
            "test/in.2825.5.txt",
            "test/in.2825.6.txt",
            "test/in.2825.7.txt",
            "test/in.2825.public_10.txt",
            "test/in.2825.public_11.txt",
            "test/in.2825.public_12.txt",
            "test/in.2825.public_13.txt",
            "test/in.2825.public_14.txt",
            "test/in.2825.public_15.txt",
            "test/in.2825.public_16.txt",
            "test/in.2825.public_17.txt",
            "test/in.2825.public_18.txt",
            "test/in.2825.public_19.txt",
            "test/in.2825.public_8.txt",
            "test/in.2825.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 51,
        "subject": "Lab-5",
        "bug_id": "2864-277519",
        "binary_path": "277519",
        "source_file": "277519_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "3",
            "public_13",
            "public_14",
            "public_17",
            "public_18",
            "public_8"
        ],
        "passing_test": [
            "1",
            "2",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_15",
            "public_19",
            "public_20",
            "public_6",
            "public_7"
        ],
        "count_neg": 6,
        "count_pos": 11,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2864.1.txt",
            "test/in.2864.2.txt",
            "test/in.2864.3.txt",
            "test/in.2864.4.txt",
            "test/in.2864.5.txt",
            "test/in.2864.public_10.txt",
            "test/in.2864.public_11.txt",
            "test/in.2864.public_13.txt",
            "test/in.2864.public_14.txt",
            "test/in.2864.public_15.txt",
            "test/in.2864.public_17.txt",
            "test/in.2864.public_18.txt",
            "test/in.2864.public_19.txt",
            "test/in.2864.public_20.txt",
            "test/in.2864.public_6.txt",
            "test/in.2864.public_7.txt",
            "test/in.2864.public_8.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 52,
        "subject": "Lab-5",
        "bug_id": "2864-277528",
        "binary_path": "277528",
        "source_file": "277528_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "3",
            "public_13",
            "public_14",
            "public_17",
            "public_18",
            "public_8"
        ],
        "passing_test": [
            "1",
            "2",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_15",
            "public_19",
            "public_20",
            "public_6",
            "public_7"
        ],
        "count_neg": 6,
        "count_pos": 11,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2864.1.txt",
            "test/in.2864.2.txt",
            "test/in.2864.3.txt",
            "test/in.2864.4.txt",
            "test/in.2864.5.txt",
            "test/in.2864.public_10.txt",
            "test/in.2864.public_11.txt",
            "test/in.2864.public_13.txt",
            "test/in.2864.public_14.txt",
            "test/in.2864.public_15.txt",
            "test/in.2864.public_17.txt",
            "test/in.2864.public_18.txt",
            "test/in.2864.public_19.txt",
            "test/in.2864.public_20.txt",
            "test/in.2864.public_6.txt",
            "test/in.2864.public_7.txt",
            "test/in.2864.public_8.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 53,
        "subject": "Lab-5",
        "bug_id": "2864-277571",
        "binary_path": "277571",
        "source_file": "277571_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_13",
            "public_14",
            "public_15",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_7",
            "public_8"
        ],
        "passing_test": [],
        "count_neg": 17,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2864.1.txt",
            "test/in.2864.2.txt",
            "test/in.2864.3.txt",
            "test/in.2864.4.txt",
            "test/in.2864.5.txt",
            "test/in.2864.public_10.txt",
            "test/in.2864.public_11.txt",
            "test/in.2864.public_13.txt",
            "test/in.2864.public_14.txt",
            "test/in.2864.public_15.txt",
            "test/in.2864.public_17.txt",
            "test/in.2864.public_18.txt",
            "test/in.2864.public_19.txt",
            "test/in.2864.public_20.txt",
            "test/in.2864.public_6.txt",
            "test/in.2864.public_7.txt",
            "test/in.2864.public_8.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 54,
        "subject": "Lab-5",
        "bug_id": "2864-277580",
        "binary_path": "277580",
        "source_file": "277580_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_13",
            "public_14",
            "public_15",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_7",
            "public_8"
        ],
        "passing_test": [],
        "count_neg": 17,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2864.1.txt",
            "test/in.2864.2.txt",
            "test/in.2864.3.txt",
            "test/in.2864.4.txt",
            "test/in.2864.5.txt",
            "test/in.2864.public_10.txt",
            "test/in.2864.public_11.txt",
            "test/in.2864.public_13.txt",
            "test/in.2864.public_14.txt",
            "test/in.2864.public_15.txt",
            "test/in.2864.public_17.txt",
            "test/in.2864.public_18.txt",
            "test/in.2864.public_19.txt",
            "test/in.2864.public_20.txt",
            "test/in.2864.public_6.txt",
            "test/in.2864.public_7.txt",
            "test/in.2864.public_8.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 55,
        "subject": "Lab-5",
        "bug_id": "2864-277591",
        "binary_path": "277591",
        "source_file": "277591_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_13",
            "public_14",
            "public_15",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_8"
        ],
        "passing_test": [
            "public_7"
        ],
        "count_neg": 16,
        "count_pos": 1,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2864.1.txt",
            "test/in.2864.2.txt",
            "test/in.2864.3.txt",
            "test/in.2864.4.txt",
            "test/in.2864.5.txt",
            "test/in.2864.public_10.txt",
            "test/in.2864.public_11.txt",
            "test/in.2864.public_13.txt",
            "test/in.2864.public_14.txt",
            "test/in.2864.public_15.txt",
            "test/in.2864.public_17.txt",
            "test/in.2864.public_18.txt",
            "test/in.2864.public_19.txt",
            "test/in.2864.public_20.txt",
            "test/in.2864.public_6.txt",
            "test/in.2864.public_7.txt",
            "test/in.2864.public_8.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 56,
        "subject": "Lab-5",
        "bug_id": "2865-277637",
        "binary_path": "277637",
        "source_file": "277637_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2865.1.txt",
            "test/in.2865.2.txt",
            "test/in.2865.3.txt",
            "test/in.2865.4.txt",
            "test/in.2865.5.txt",
            "test/in.2865.public_10.txt",
            "test/in.2865.public_11.txt",
            "test/in.2865.public_12.txt",
            "test/in.2865.public_13.txt",
            "test/in.2865.public_14.txt",
            "test/in.2865.public_15.txt",
            "test/in.2865.public_16.txt",
            "test/in.2865.public_17.txt",
            "test/in.2865.public_18.txt",
            "test/in.2865.public_19.txt",
            "test/in.2865.public_20.txt",
            "test/in.2865.public_6.txt",
            "test/in.2865.public_7.txt",
            "test/in.2865.public_8.txt",
            "test/in.2865.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 57,
        "subject": "Lab-5",
        "bug_id": "2865-277685",
        "binary_path": "277685",
        "source_file": "277685_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "5",
            "public_10",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_7",
            "public_9"
        ],
        "passing_test": [
            "4",
            "public_11",
            "public_20",
            "public_6",
            "public_8"
        ],
        "count_neg": 15,
        "count_pos": 5,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2865.1.txt",
            "test/in.2865.2.txt",
            "test/in.2865.3.txt",
            "test/in.2865.4.txt",
            "test/in.2865.5.txt",
            "test/in.2865.public_10.txt",
            "test/in.2865.public_11.txt",
            "test/in.2865.public_12.txt",
            "test/in.2865.public_13.txt",
            "test/in.2865.public_14.txt",
            "test/in.2865.public_15.txt",
            "test/in.2865.public_16.txt",
            "test/in.2865.public_17.txt",
            "test/in.2865.public_18.txt",
            "test/in.2865.public_19.txt",
            "test/in.2865.public_20.txt",
            "test/in.2865.public_6.txt",
            "test/in.2865.public_7.txt",
            "test/in.2865.public_8.txt",
            "test/in.2865.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 58,
        "subject": "Lab-5",
        "bug_id": "2865-277711",
        "binary_path": "277711",
        "source_file": "277711_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2865.1.txt",
            "test/in.2865.2.txt",
            "test/in.2865.3.txt",
            "test/in.2865.4.txt",
            "test/in.2865.5.txt",
            "test/in.2865.public_10.txt",
            "test/in.2865.public_11.txt",
            "test/in.2865.public_12.txt",
            "test/in.2865.public_13.txt",
            "test/in.2865.public_14.txt",
            "test/in.2865.public_15.txt",
            "test/in.2865.public_16.txt",
            "test/in.2865.public_17.txt",
            "test/in.2865.public_18.txt",
            "test/in.2865.public_19.txt",
            "test/in.2865.public_20.txt",
            "test/in.2865.public_6.txt",
            "test/in.2865.public_7.txt",
            "test/in.2865.public_8.txt",
            "test/in.2865.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 59,
        "subject": "Lab-5",
        "bug_id": "2866-277780",
        "binary_path": "277780",
        "source_file": "277780_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2866.1.txt",
            "test/in.2866.2.txt",
            "test/in.2866.3.txt",
            "test/in.2866.4.txt",
            "test/in.2866.5.txt",
            "test/in.2866.6.txt",
            "test/in.2866.7.txt",
            "test/in.2866.8.txt",
            "test/in.2866.9.txt",
            "test/in.2866.public_10.txt",
            "test/in.2866.public_11.txt",
            "test/in.2866.public_12.txt",
            "test/in.2866.public_13.txt",
            "test/in.2866.public_14.txt",
            "test/in.2866.public_15.txt",
            "test/in.2866.public_16.txt",
            "test/in.2866.public_17.txt",
            "test/in.2866.public_18.txt",
            "test/in.2866.public_19.txt",
            "test/in.2866.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 60,
        "subject": "Lab-5",
        "bug_id": "2866-277802",
        "binary_path": "277802",
        "source_file": "277802_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2866.1.txt",
            "test/in.2866.2.txt",
            "test/in.2866.3.txt",
            "test/in.2866.4.txt",
            "test/in.2866.5.txt",
            "test/in.2866.6.txt",
            "test/in.2866.7.txt",
            "test/in.2866.8.txt",
            "test/in.2866.9.txt",
            "test/in.2866.public_10.txt",
            "test/in.2866.public_11.txt",
            "test/in.2866.public_12.txt",
            "test/in.2866.public_13.txt",
            "test/in.2866.public_14.txt",
            "test/in.2866.public_15.txt",
            "test/in.2866.public_16.txt",
            "test/in.2866.public_17.txt",
            "test/in.2866.public_18.txt",
            "test/in.2866.public_19.txt",
            "test/in.2866.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 61,
        "subject": "Lab-6",
        "bug_id": "2932-279950",
        "binary_path": "279950",
        "source_file": "279950_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_8"
        ],
        "passing_test": [],
        "count_neg": 19,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2932.1.txt",
            "test/in.2932.2.txt",
            "test/in.2932.3.txt",
            "test/in.2932.4.txt",
            "test/in.2932.5.txt",
            "test/in.2932.6.txt",
            "test/in.2932.7.txt",
            "test/in.2932.public_10.txt",
            "test/in.2932.public_11.txt",
            "test/in.2932.public_12.txt",
            "test/in.2932.public_13.txt",
            "test/in.2932.public_14.txt",
            "test/in.2932.public_15.txt",
            "test/in.2932.public_16.txt",
            "test/in.2932.public_17.txt",
            "test/in.2932.public_18.txt",
            "test/in.2932.public_19.txt",
            "test/in.2932.public_20.txt",
            "test/in.2932.public_8.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 62,
        "subject": "Lab-6",
        "bug_id": "2932-279986",
        "binary_path": "279986",
        "source_file": "279986_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_8"
        ],
        "passing_test": [],
        "count_neg": 19,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2932.1.txt",
            "test/in.2932.2.txt",
            "test/in.2932.3.txt",
            "test/in.2932.4.txt",
            "test/in.2932.5.txt",
            "test/in.2932.6.txt",
            "test/in.2932.7.txt",
            "test/in.2932.public_10.txt",
            "test/in.2932.public_11.txt",
            "test/in.2932.public_12.txt",
            "test/in.2932.public_13.txt",
            "test/in.2932.public_14.txt",
            "test/in.2932.public_15.txt",
            "test/in.2932.public_16.txt",
            "test/in.2932.public_17.txt",
            "test/in.2932.public_18.txt",
            "test/in.2932.public_19.txt",
            "test/in.2932.public_20.txt",
            "test/in.2932.public_8.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 63,
        "subject": "Lab-6",
        "bug_id": "2932-280004",
        "binary_path": "280004",
        "source_file": "280004_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_8"
        ],
        "passing_test": [],
        "count_neg": 19,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2932.1.txt",
            "test/in.2932.2.txt",
            "test/in.2932.3.txt",
            "test/in.2932.4.txt",
            "test/in.2932.5.txt",
            "test/in.2932.6.txt",
            "test/in.2932.7.txt",
            "test/in.2932.public_10.txt",
            "test/in.2932.public_11.txt",
            "test/in.2932.public_12.txt",
            "test/in.2932.public_13.txt",
            "test/in.2932.public_14.txt",
            "test/in.2932.public_15.txt",
            "test/in.2932.public_16.txt",
            "test/in.2932.public_17.txt",
            "test/in.2932.public_18.txt",
            "test/in.2932.public_19.txt",
            "test/in.2932.public_20.txt",
            "test/in.2932.public_8.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 64,
        "subject": "Lab-6",
        "bug_id": "2932-280017",
        "binary_path": "280017",
        "source_file": "280017_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_8"
        ],
        "passing_test": [],
        "count_neg": 19,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2932.1.txt",
            "test/in.2932.2.txt",
            "test/in.2932.3.txt",
            "test/in.2932.4.txt",
            "test/in.2932.5.txt",
            "test/in.2932.6.txt",
            "test/in.2932.7.txt",
            "test/in.2932.public_10.txt",
            "test/in.2932.public_11.txt",
            "test/in.2932.public_12.txt",
            "test/in.2932.public_13.txt",
            "test/in.2932.public_14.txt",
            "test/in.2932.public_15.txt",
            "test/in.2932.public_16.txt",
            "test/in.2932.public_17.txt",
            "test/in.2932.public_18.txt",
            "test/in.2932.public_19.txt",
            "test/in.2932.public_20.txt",
            "test/in.2932.public_8.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 65,
        "subject": "Lab-6",
        "bug_id": "2933-280079",
        "binary_path": "280079",
        "source_file": "280079_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_12",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 18,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2933.1.txt",
            "test/in.2933.2.txt",
            "test/in.2933.3.txt",
            "test/in.2933.4.txt",
            "test/in.2933.5.txt",
            "test/in.2933.public_10.txt",
            "test/in.2933.public_11.txt",
            "test/in.2933.public_12.txt",
            "test/in.2933.public_14.txt",
            "test/in.2933.public_15.txt",
            "test/in.2933.public_16.txt",
            "test/in.2933.public_17.txt",
            "test/in.2933.public_18.txt",
            "test/in.2933.public_19.txt",
            "test/in.2933.public_20.txt",
            "test/in.2933.public_6.txt",
            "test/in.2933.public_8.txt",
            "test/in.2933.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 66,
        "subject": "Lab-6",
        "bug_id": "2933-280127",
        "binary_path": "280127",
        "source_file": "280127_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "2",
            "3",
            "4",
            "public_10",
            "public_11",
            "public_16",
            "public_17",
            "public_8"
        ],
        "passing_test": [
            "1",
            "5",
            "public_12",
            "public_14",
            "public_15",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_9"
        ],
        "count_neg": 8,
        "count_pos": 10,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2933.1.txt",
            "test/in.2933.2.txt",
            "test/in.2933.3.txt",
            "test/in.2933.4.txt",
            "test/in.2933.5.txt",
            "test/in.2933.public_10.txt",
            "test/in.2933.public_11.txt",
            "test/in.2933.public_12.txt",
            "test/in.2933.public_14.txt",
            "test/in.2933.public_15.txt",
            "test/in.2933.public_16.txt",
            "test/in.2933.public_17.txt",
            "test/in.2933.public_18.txt",
            "test/in.2933.public_19.txt",
            "test/in.2933.public_20.txt",
            "test/in.2933.public_6.txt",
            "test/in.2933.public_8.txt",
            "test/in.2933.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 67,
        "subject": "Lab-6",
        "bug_id": "2934-280208",
        "binary_path": "280208",
        "source_file": "280208_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_15",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 18,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2934.1.txt",
            "test/in.2934.2.txt",
            "test/in.2934.3.txt",
            "test/in.2934.4.txt",
            "test/in.2934.5.txt",
            "test/in.2934.public_10.txt",
            "test/in.2934.public_11.txt",
            "test/in.2934.public_12.txt",
            "test/in.2934.public_13.txt",
            "test/in.2934.public_15.txt",
            "test/in.2934.public_17.txt",
            "test/in.2934.public_18.txt",
            "test/in.2934.public_19.txt",
            "test/in.2934.public_20.txt",
            "test/in.2934.public_6.txt",
            "test/in.2934.public_7.txt",
            "test/in.2934.public_8.txt",
            "test/in.2934.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 68,
        "subject": "Lab-6",
        "bug_id": "2934-280226",
        "binary_path": "280226",
        "source_file": "280226_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_15",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 18,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2934.1.txt",
            "test/in.2934.2.txt",
            "test/in.2934.3.txt",
            "test/in.2934.4.txt",
            "test/in.2934.5.txt",
            "test/in.2934.public_10.txt",
            "test/in.2934.public_11.txt",
            "test/in.2934.public_12.txt",
            "test/in.2934.public_13.txt",
            "test/in.2934.public_15.txt",
            "test/in.2934.public_17.txt",
            "test/in.2934.public_18.txt",
            "test/in.2934.public_19.txt",
            "test/in.2934.public_20.txt",
            "test/in.2934.public_6.txt",
            "test/in.2934.public_7.txt",
            "test/in.2934.public_8.txt",
            "test/in.2934.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 69,
        "subject": "Lab-6",
        "bug_id": "2934-280238",
        "binary_path": "280238",
        "source_file": "280238_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_15",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 18,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2934.1.txt",
            "test/in.2934.2.txt",
            "test/in.2934.3.txt",
            "test/in.2934.4.txt",
            "test/in.2934.5.txt",
            "test/in.2934.public_10.txt",
            "test/in.2934.public_11.txt",
            "test/in.2934.public_12.txt",
            "test/in.2934.public_13.txt",
            "test/in.2934.public_15.txt",
            "test/in.2934.public_17.txt",
            "test/in.2934.public_18.txt",
            "test/in.2934.public_19.txt",
            "test/in.2934.public_20.txt",
            "test/in.2934.public_6.txt",
            "test/in.2934.public_7.txt",
            "test/in.2934.public_8.txt",
            "test/in.2934.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 70,
        "subject": "Lab-6",
        "bug_id": "2935-280333",
        "binary_path": "280333",
        "source_file": "280333_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "public_10",
            "public_11",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_19",
            "public_20",
            "public_5",
            "public_8",
            "public_9"
        ],
        "passing_test": [
            "public_12",
            "public_6",
            "public_7"
        ],
        "count_neg": 16,
        "count_pos": 3,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.2935.1.txt",
            "test/in.2935.2.txt",
            "test/in.2935.3.txt",
            "test/in.2935.4.txt",
            "test/in.2935.public_10.txt",
            "test/in.2935.public_11.txt",
            "test/in.2935.public_12.txt",
            "test/in.2935.public_13.txt",
            "test/in.2935.public_14.txt",
            "test/in.2935.public_15.txt",
            "test/in.2935.public_16.txt",
            "test/in.2935.public_17.txt",
            "test/in.2935.public_19.txt",
            "test/in.2935.public_20.txt",
            "test/in.2935.public_5.txt",
            "test/in.2935.public_6.txt",
            "test/in.2935.public_7.txt",
            "test/in.2935.public_8.txt",
            "test/in.2935.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 71,
        "subject": "Lab-7",
        "bug_id": "3075-295416",
        "binary_path": "295416",
        "source_file": "295416_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "7",
            "public_13",
            "public_14",
            "public_15",
            "public_16"
        ],
        "passing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "8",
            "9",
            "public_10",
            "public_11",
            "public_12",
            "public_19",
            "public_20"
        ],
        "count_neg": 5,
        "count_pos": 13,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3075.1.txt",
            "test/in.3075.2.txt",
            "test/in.3075.3.txt",
            "test/in.3075.4.txt",
            "test/in.3075.5.txt",
            "test/in.3075.6.txt",
            "test/in.3075.7.txt",
            "test/in.3075.8.txt",
            "test/in.3075.9.txt",
            "test/in.3075.public_10.txt",
            "test/in.3075.public_11.txt",
            "test/in.3075.public_12.txt",
            "test/in.3075.public_13.txt",
            "test/in.3075.public_14.txt",
            "test/in.3075.public_15.txt",
            "test/in.3075.public_16.txt",
            "test/in.3075.public_19.txt",
            "test/in.3075.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 72,
        "subject": "Lab-7",
        "bug_id": "3075-295450",
        "binary_path": "295450",
        "source_file": "295450_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "7",
            "public_13",
            "public_14",
            "public_15",
            "public_16"
        ],
        "passing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "8",
            "9",
            "public_10",
            "public_11",
            "public_12",
            "public_19",
            "public_20"
        ],
        "count_neg": 5,
        "count_pos": 13,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3075.1.txt",
            "test/in.3075.2.txt",
            "test/in.3075.3.txt",
            "test/in.3075.4.txt",
            "test/in.3075.5.txt",
            "test/in.3075.6.txt",
            "test/in.3075.7.txt",
            "test/in.3075.8.txt",
            "test/in.3075.9.txt",
            "test/in.3075.public_10.txt",
            "test/in.3075.public_11.txt",
            "test/in.3075.public_12.txt",
            "test/in.3075.public_13.txt",
            "test/in.3075.public_14.txt",
            "test/in.3075.public_15.txt",
            "test/in.3075.public_16.txt",
            "test/in.3075.public_19.txt",
            "test/in.3075.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 73,
        "subject": "Lab-7",
        "bug_id": "3075-295460",
        "binary_path": "295460",
        "source_file": "295460_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "7",
            "public_13",
            "public_14",
            "public_15",
            "public_16"
        ],
        "passing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "8",
            "9",
            "public_10",
            "public_11",
            "public_12",
            "public_19",
            "public_20"
        ],
        "count_neg": 5,
        "count_pos": 13,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3075.1.txt",
            "test/in.3075.2.txt",
            "test/in.3075.3.txt",
            "test/in.3075.4.txt",
            "test/in.3075.5.txt",
            "test/in.3075.6.txt",
            "test/in.3075.7.txt",
            "test/in.3075.8.txt",
            "test/in.3075.9.txt",
            "test/in.3075.public_10.txt",
            "test/in.3075.public_11.txt",
            "test/in.3075.public_12.txt",
            "test/in.3075.public_13.txt",
            "test/in.3075.public_14.txt",
            "test/in.3075.public_15.txt",
            "test/in.3075.public_16.txt",
            "test/in.3075.public_19.txt",
            "test/in.3075.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 74,
        "subject": "Lab-7",
        "bug_id": "3076-295675",
        "binary_path": "295675",
        "source_file": "295675_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3076.1.txt",
            "test/in.3076.2.txt",
            "test/in.3076.3.txt",
            "test/in.3076.4.txt",
            "test/in.3076.5.txt",
            "test/in.3076.6.txt",
            "test/in.3076.7.txt",
            "test/in.3076.8.txt",
            "test/in.3076.9.txt",
            "test/in.3076.public_10.txt",
            "test/in.3076.public_11.txt",
            "test/in.3076.public_12.txt",
            "test/in.3076.public_13.txt",
            "test/in.3076.public_14.txt",
            "test/in.3076.public_15.txt",
            "test/in.3076.public_16.txt",
            "test/in.3076.public_17.txt",
            "test/in.3076.public_18.txt",
            "test/in.3076.public_19.txt",
            "test/in.3076.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 75,
        "subject": "Lab-7",
        "bug_id": "3076-295686",
        "binary_path": "295686",
        "source_file": "295686_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20"
        ],
        "passing_test": [
            "9"
        ],
        "count_neg": 19,
        "count_pos": 1,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3076.1.txt",
            "test/in.3076.2.txt",
            "test/in.3076.3.txt",
            "test/in.3076.4.txt",
            "test/in.3076.5.txt",
            "test/in.3076.6.txt",
            "test/in.3076.7.txt",
            "test/in.3076.8.txt",
            "test/in.3076.9.txt",
            "test/in.3076.public_10.txt",
            "test/in.3076.public_11.txt",
            "test/in.3076.public_12.txt",
            "test/in.3076.public_13.txt",
            "test/in.3076.public_14.txt",
            "test/in.3076.public_15.txt",
            "test/in.3076.public_16.txt",
            "test/in.3076.public_17.txt",
            "test/in.3076.public_18.txt",
            "test/in.3076.public_19.txt",
            "test/in.3076.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 76,
        "subject": "Lab-7",
        "bug_id": "3076-295698",
        "binary_path": "295698",
        "source_file": "295698_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20"
        ],
        "passing_test": [
            "9"
        ],
        "count_neg": 19,
        "count_pos": 1,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3076.1.txt",
            "test/in.3076.2.txt",
            "test/in.3076.3.txt",
            "test/in.3076.4.txt",
            "test/in.3076.5.txt",
            "test/in.3076.6.txt",
            "test/in.3076.7.txt",
            "test/in.3076.8.txt",
            "test/in.3076.9.txt",
            "test/in.3076.public_10.txt",
            "test/in.3076.public_11.txt",
            "test/in.3076.public_12.txt",
            "test/in.3076.public_13.txt",
            "test/in.3076.public_14.txt",
            "test/in.3076.public_15.txt",
            "test/in.3076.public_16.txt",
            "test/in.3076.public_17.txt",
            "test/in.3076.public_18.txt",
            "test/in.3076.public_19.txt",
            "test/in.3076.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 77,
        "subject": "Lab-7",
        "bug_id": "3076-295738",
        "binary_path": "295738",
        "source_file": "295738_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "9"
        ],
        "passing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20"
        ],
        "count_neg": 1,
        "count_pos": 19,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3076.1.txt",
            "test/in.3076.2.txt",
            "test/in.3076.3.txt",
            "test/in.3076.4.txt",
            "test/in.3076.5.txt",
            "test/in.3076.6.txt",
            "test/in.3076.7.txt",
            "test/in.3076.8.txt",
            "test/in.3076.9.txt",
            "test/in.3076.public_10.txt",
            "test/in.3076.public_11.txt",
            "test/in.3076.public_12.txt",
            "test/in.3076.public_13.txt",
            "test/in.3076.public_14.txt",
            "test/in.3076.public_15.txt",
            "test/in.3076.public_16.txt",
            "test/in.3076.public_17.txt",
            "test/in.3076.public_18.txt",
            "test/in.3076.public_19.txt",
            "test/in.3076.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 78,
        "subject": "Lab-7",
        "bug_id": "3077-295929",
        "binary_path": "295929",
        "source_file": "295929_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3077.1.txt",
            "test/in.3077.2.txt",
            "test/in.3077.3.txt",
            "test/in.3077.4.txt",
            "test/in.3077.5.txt",
            "test/in.3077.6.txt",
            "test/in.3077.7.txt",
            "test/in.3077.8.txt",
            "test/in.3077.public_10.txt",
            "test/in.3077.public_11.txt",
            "test/in.3077.public_12.txt",
            "test/in.3077.public_13.txt",
            "test/in.3077.public_14.txt",
            "test/in.3077.public_15.txt",
            "test/in.3077.public_16.txt",
            "test/in.3077.public_17.txt",
            "test/in.3077.public_18.txt",
            "test/in.3077.public_19.txt",
            "test/in.3077.public_20.txt",
            "test/in.3077.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 79,
        "subject": "Lab-7",
        "bug_id": "3077-295949",
        "binary_path": "295949",
        "source_file": "295949_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3077.1.txt",
            "test/in.3077.2.txt",
            "test/in.3077.3.txt",
            "test/in.3077.4.txt",
            "test/in.3077.5.txt",
            "test/in.3077.6.txt",
            "test/in.3077.7.txt",
            "test/in.3077.8.txt",
            "test/in.3077.public_10.txt",
            "test/in.3077.public_11.txt",
            "test/in.3077.public_12.txt",
            "test/in.3077.public_13.txt",
            "test/in.3077.public_14.txt",
            "test/in.3077.public_15.txt",
            "test/in.3077.public_16.txt",
            "test/in.3077.public_17.txt",
            "test/in.3077.public_18.txt",
            "test/in.3077.public_19.txt",
            "test/in.3077.public_20.txt",
            "test/in.3077.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 80,
        "subject": "Lab-7",
        "bug_id": "3077-295971",
        "binary_path": "295971",
        "source_file": "295971_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3077.1.txt",
            "test/in.3077.2.txt",
            "test/in.3077.3.txt",
            "test/in.3077.4.txt",
            "test/in.3077.5.txt",
            "test/in.3077.6.txt",
            "test/in.3077.7.txt",
            "test/in.3077.8.txt",
            "test/in.3077.public_10.txt",
            "test/in.3077.public_11.txt",
            "test/in.3077.public_12.txt",
            "test/in.3077.public_13.txt",
            "test/in.3077.public_14.txt",
            "test/in.3077.public_15.txt",
            "test/in.3077.public_16.txt",
            "test/in.3077.public_17.txt",
            "test/in.3077.public_18.txt",
            "test/in.3077.public_19.txt",
            "test/in.3077.public_20.txt",
            "test/in.3077.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 81,
        "subject": "Lab-8",
        "bug_id": "3081-297318",
        "binary_path": "297318",
        "source_file": "297318_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "public_10",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3081.1.txt",
            "test/in.3081.2.txt",
            "test/in.3081.3.txt",
            "test/in.3081.4.txt",
            "test/in.3081.5.txt",
            "test/in.3081.6.txt",
            "test/in.3081.7.txt",
            "test/in.3081.8.txt",
            "test/in.3081.public_10.txt",
            "test/in.3081.public_12.txt",
            "test/in.3081.public_13.txt",
            "test/in.3081.public_14.txt",
            "test/in.3081.public_15.txt",
            "test/in.3081.public_16.txt",
            "test/in.3081.public_17.txt",
            "test/in.3081.public_18.txt",
            "test/in.3081.public_19.txt",
            "test/in.3081.public_20.txt",
            "test/in.3081.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 82,
        "subject": "Lab-8",
        "bug_id": "3081-297349",
        "binary_path": "297349",
        "source_file": "297349_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "public_10",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3081.1.txt",
            "test/in.3081.2.txt",
            "test/in.3081.3.txt",
            "test/in.3081.4.txt",
            "test/in.3081.5.txt",
            "test/in.3081.6.txt",
            "test/in.3081.7.txt",
            "test/in.3081.8.txt",
            "test/in.3081.public_10.txt",
            "test/in.3081.public_12.txt",
            "test/in.3081.public_13.txt",
            "test/in.3081.public_14.txt",
            "test/in.3081.public_15.txt",
            "test/in.3081.public_16.txt",
            "test/in.3081.public_17.txt",
            "test/in.3081.public_18.txt",
            "test/in.3081.public_19.txt",
            "test/in.3081.public_20.txt",
            "test/in.3081.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 83,
        "subject": "Lab-8",
        "bug_id": "3082-297430",
        "binary_path": "297430",
        "source_file": "297430_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_7",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3082.1.txt",
            "test/in.3082.2.txt",
            "test/in.3082.3.txt",
            "test/in.3082.4.txt",
            "test/in.3082.5.txt",
            "test/in.3082.public_10.txt",
            "test/in.3082.public_11.txt",
            "test/in.3082.public_13.txt",
            "test/in.3082.public_14.txt",
            "test/in.3082.public_15.txt",
            "test/in.3082.public_16.txt",
            "test/in.3082.public_17.txt",
            "test/in.3082.public_18.txt",
            "test/in.3082.public_19.txt",
            "test/in.3082.public_20.txt",
            "test/in.3082.public_6.txt",
            "test/in.3082.public_7.txt",
            "test/in.3082.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 84,
        "subject": "Lab-8",
        "bug_id": "3082-297453",
        "binary_path": "297453",
        "source_file": "297453_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_7",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3082.1.txt",
            "test/in.3082.2.txt",
            "test/in.3082.3.txt",
            "test/in.3082.4.txt",
            "test/in.3082.5.txt",
            "test/in.3082.public_10.txt",
            "test/in.3082.public_11.txt",
            "test/in.3082.public_13.txt",
            "test/in.3082.public_14.txt",
            "test/in.3082.public_15.txt",
            "test/in.3082.public_16.txt",
            "test/in.3082.public_17.txt",
            "test/in.3082.public_18.txt",
            "test/in.3082.public_19.txt",
            "test/in.3082.public_20.txt",
            "test/in.3082.public_6.txt",
            "test/in.3082.public_7.txt",
            "test/in.3082.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 85,
        "subject": "Lab-8",
        "bug_id": "3082-297466",
        "binary_path": "297466",
        "source_file": "297466_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "public_10",
            "public_11",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_6",
            "public_7",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3082.1.txt",
            "test/in.3082.2.txt",
            "test/in.3082.3.txt",
            "test/in.3082.4.txt",
            "test/in.3082.5.txt",
            "test/in.3082.public_10.txt",
            "test/in.3082.public_11.txt",
            "test/in.3082.public_13.txt",
            "test/in.3082.public_14.txt",
            "test/in.3082.public_15.txt",
            "test/in.3082.public_16.txt",
            "test/in.3082.public_17.txt",
            "test/in.3082.public_18.txt",
            "test/in.3082.public_19.txt",
            "test/in.3082.public_20.txt",
            "test/in.3082.public_6.txt",
            "test/in.3082.public_7.txt",
            "test/in.3082.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 86,
        "subject": "Lab-8",
        "bug_id": "3083-297563",
        "binary_path": "297563",
        "source_file": "297563_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "public_10",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 18,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3083.1.txt",
            "test/in.3083.2.txt",
            "test/in.3083.3.txt",
            "test/in.3083.4.txt",
            "test/in.3083.5.txt",
            "test/in.3083.6.txt",
            "test/in.3083.7.txt",
            "test/in.3083.public_10.txt",
            "test/in.3083.public_12.txt",
            "test/in.3083.public_13.txt",
            "test/in.3083.public_14.txt",
            "test/in.3083.public_15.txt",
            "test/in.3083.public_16.txt",
            "test/in.3083.public_17.txt",
            "test/in.3083.public_18.txt",
            "test/in.3083.public_19.txt",
            "test/in.3083.public_20.txt",
            "test/in.3083.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 87,
        "subject": "Lab-8",
        "bug_id": "3084-297672",
        "binary_path": "297672",
        "source_file": "297672_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "3",
            "public_17",
            "public_20"
        ],
        "passing_test": [
            "1",
            "2",
            "4",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_18",
            "public_19",
            "public_5",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "count_neg": 3,
        "count_pos": 17,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3084.1.txt",
            "test/in.3084.2.txt",
            "test/in.3084.3.txt",
            "test/in.3084.4.txt",
            "test/in.3084.public_10.txt",
            "test/in.3084.public_11.txt",
            "test/in.3084.public_12.txt",
            "test/in.3084.public_13.txt",
            "test/in.3084.public_14.txt",
            "test/in.3084.public_15.txt",
            "test/in.3084.public_16.txt",
            "test/in.3084.public_17.txt",
            "test/in.3084.public_18.txt",
            "test/in.3084.public_19.txt",
            "test/in.3084.public_20.txt",
            "test/in.3084.public_5.txt",
            "test/in.3084.public_6.txt",
            "test/in.3084.public_7.txt",
            "test/in.3084.public_8.txt",
            "test/in.3084.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 88,
        "subject": "Lab-8",
        "bug_id": "3084-297698",
        "binary_path": "297698",
        "source_file": "297698_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "3",
            "public_17",
            "public_20"
        ],
        "passing_test": [
            "1",
            "2",
            "4",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_18",
            "public_19",
            "public_5",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "count_neg": 3,
        "count_pos": 17,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3084.1.txt",
            "test/in.3084.2.txt",
            "test/in.3084.3.txt",
            "test/in.3084.4.txt",
            "test/in.3084.public_10.txt",
            "test/in.3084.public_11.txt",
            "test/in.3084.public_12.txt",
            "test/in.3084.public_13.txt",
            "test/in.3084.public_14.txt",
            "test/in.3084.public_15.txt",
            "test/in.3084.public_16.txt",
            "test/in.3084.public_17.txt",
            "test/in.3084.public_18.txt",
            "test/in.3084.public_19.txt",
            "test/in.3084.public_20.txt",
            "test/in.3084.public_5.txt",
            "test/in.3084.public_6.txt",
            "test/in.3084.public_7.txt",
            "test/in.3084.public_8.txt",
            "test/in.3084.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 89,
        "subject": "Lab-8",
        "bug_id": "3084-297732",
        "binary_path": "297732",
        "source_file": "297732_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_5",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3084.1.txt",
            "test/in.3084.2.txt",
            "test/in.3084.3.txt",
            "test/in.3084.4.txt",
            "test/in.3084.public_10.txt",
            "test/in.3084.public_11.txt",
            "test/in.3084.public_12.txt",
            "test/in.3084.public_13.txt",
            "test/in.3084.public_14.txt",
            "test/in.3084.public_15.txt",
            "test/in.3084.public_16.txt",
            "test/in.3084.public_17.txt",
            "test/in.3084.public_18.txt",
            "test/in.3084.public_19.txt",
            "test/in.3084.public_20.txt",
            "test/in.3084.public_5.txt",
            "test/in.3084.public_6.txt",
            "test/in.3084.public_7.txt",
            "test/in.3084.public_8.txt",
            "test/in.3084.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 90,
        "subject": "Lab-8",
        "bug_id": "3084-297748",
        "binary_path": "297748",
        "source_file": "297748_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_5",
            "public_6",
            "public_7",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3084.1.txt",
            "test/in.3084.2.txt",
            "test/in.3084.3.txt",
            "test/in.3084.4.txt",
            "test/in.3084.public_10.txt",
            "test/in.3084.public_11.txt",
            "test/in.3084.public_12.txt",
            "test/in.3084.public_13.txt",
            "test/in.3084.public_14.txt",
            "test/in.3084.public_15.txt",
            "test/in.3084.public_16.txt",
            "test/in.3084.public_17.txt",
            "test/in.3084.public_18.txt",
            "test/in.3084.public_19.txt",
            "test/in.3084.public_20.txt",
            "test/in.3084.public_5.txt",
            "test/in.3084.public_6.txt",
            "test/in.3084.public_7.txt",
            "test/in.3084.public_8.txt",
            "test/in.3084.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 91,
        "subject": "Lab-9",
        "bug_id": "3105-300001",
        "binary_path": "300001",
        "source_file": "300001_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "public_10",
            "public_11",
            "public_12",
            "public_14",
            "public_15",
            "public_18",
            "public_20",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 12,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3105.1.txt",
            "test/in.3105.2.txt",
            "test/in.3105.3.txt",
            "test/in.3105.public_10.txt",
            "test/in.3105.public_11.txt",
            "test/in.3105.public_12.txt",
            "test/in.3105.public_14.txt",
            "test/in.3105.public_15.txt",
            "test/in.3105.public_18.txt",
            "test/in.3105.public_20.txt",
            "test/in.3105.public_8.txt",
            "test/in.3105.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 92,
        "subject": "Lab-9",
        "bug_id": "3105-300019",
        "binary_path": "300019",
        "source_file": "300019_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "public_10",
            "public_11",
            "public_12",
            "public_14",
            "public_15",
            "public_18",
            "public_20",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 12,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3105.1.txt",
            "test/in.3105.2.txt",
            "test/in.3105.3.txt",
            "test/in.3105.public_10.txt",
            "test/in.3105.public_11.txt",
            "test/in.3105.public_12.txt",
            "test/in.3105.public_14.txt",
            "test/in.3105.public_15.txt",
            "test/in.3105.public_18.txt",
            "test/in.3105.public_20.txt",
            "test/in.3105.public_8.txt",
            "test/in.3105.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 93,
        "subject": "Lab-9",
        "bug_id": "3105-300058",
        "binary_path": "300058",
        "source_file": "300058_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "public_10",
            "public_11",
            "public_12",
            "public_14",
            "public_15",
            "public_18",
            "public_20",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 12,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3105.1.txt",
            "test/in.3105.2.txt",
            "test/in.3105.3.txt",
            "test/in.3105.public_10.txt",
            "test/in.3105.public_11.txt",
            "test/in.3105.public_12.txt",
            "test/in.3105.public_14.txt",
            "test/in.3105.public_15.txt",
            "test/in.3105.public_18.txt",
            "test/in.3105.public_20.txt",
            "test/in.3105.public_8.txt",
            "test/in.3105.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 94,
        "subject": "Lab-9",
        "bug_id": "3106-300255",
        "binary_path": "300255",
        "source_file": "300255_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_5",
            "public_6",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3106.1.txt",
            "test/in.3106.2.txt",
            "test/in.3106.3.txt",
            "test/in.3106.4.txt",
            "test/in.3106.public_10.txt",
            "test/in.3106.public_11.txt",
            "test/in.3106.public_12.txt",
            "test/in.3106.public_13.txt",
            "test/in.3106.public_14.txt",
            "test/in.3106.public_15.txt",
            "test/in.3106.public_16.txt",
            "test/in.3106.public_17.txt",
            "test/in.3106.public_18.txt",
            "test/in.3106.public_19.txt",
            "test/in.3106.public_20.txt",
            "test/in.3106.public_5.txt",
            "test/in.3106.public_6.txt",
            "test/in.3106.public_8.txt",
            "test/in.3106.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 95,
        "subject": "Lab-9",
        "bug_id": "3106-300294",
        "binary_path": "300294",
        "source_file": "300294_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_5",
            "public_6",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3106.1.txt",
            "test/in.3106.2.txt",
            "test/in.3106.3.txt",
            "test/in.3106.4.txt",
            "test/in.3106.public_10.txt",
            "test/in.3106.public_11.txt",
            "test/in.3106.public_12.txt",
            "test/in.3106.public_13.txt",
            "test/in.3106.public_14.txt",
            "test/in.3106.public_15.txt",
            "test/in.3106.public_16.txt",
            "test/in.3106.public_17.txt",
            "test/in.3106.public_18.txt",
            "test/in.3106.public_19.txt",
            "test/in.3106.public_20.txt",
            "test/in.3106.public_5.txt",
            "test/in.3106.public_6.txt",
            "test/in.3106.public_8.txt",
            "test/in.3106.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 96,
        "subject": "Lab-9",
        "bug_id": "3106-300324",
        "binary_path": "300324",
        "source_file": "300324_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20",
            "public_5",
            "public_6",
            "public_8",
            "public_9"
        ],
        "passing_test": [],
        "count_neg": 20,
        "count_pos": 0,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3106.1.txt",
            "test/in.3106.2.txt",
            "test/in.3106.3.txt",
            "test/in.3106.4.txt",
            "test/in.3106.public_10.txt",
            "test/in.3106.public_11.txt",
            "test/in.3106.public_12.txt",
            "test/in.3106.public_13.txt",
            "test/in.3106.public_14.txt",
            "test/in.3106.public_15.txt",
            "test/in.3106.public_16.txt",
            "test/in.3106.public_17.txt",
            "test/in.3106.public_18.txt",
            "test/in.3106.public_19.txt",
            "test/in.3106.public_20.txt",
            "test/in.3106.public_5.txt",
            "test/in.3106.public_6.txt",
            "test/in.3106.public_8.txt",
            "test/in.3106.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 97,
        "subject": "Lab-9",
        "bug_id": "3107-300501",
        "binary_path": "300501",
        "source_file": "300501_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "2",
            "3",
            "4",
            "6",
            "8",
            "public_16",
            "public_17",
            "public_19"
        ],
        "passing_test": [
            "1",
            "5",
            "7",
            "9",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_18",
            "public_20"
        ],
        "count_neg": 8,
        "count_pos": 12,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3107.1.txt",
            "test/in.3107.2.txt",
            "test/in.3107.3.txt",
            "test/in.3107.4.txt",
            "test/in.3107.5.txt",
            "test/in.3107.6.txt",
            "test/in.3107.7.txt",
            "test/in.3107.8.txt",
            "test/in.3107.9.txt",
            "test/in.3107.public_10.txt",
            "test/in.3107.public_11.txt",
            "test/in.3107.public_12.txt",
            "test/in.3107.public_13.txt",
            "test/in.3107.public_14.txt",
            "test/in.3107.public_15.txt",
            "test/in.3107.public_16.txt",
            "test/in.3107.public_17.txt",
            "test/in.3107.public_18.txt",
            "test/in.3107.public_19.txt",
            "test/in.3107.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 98,
        "subject": "Lab-9",
        "bug_id": "3107-300536",
        "binary_path": "300536",
        "source_file": "300536_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "2",
            "3",
            "4",
            "6",
            "8",
            "public_16",
            "public_17",
            "public_20"
        ],
        "passing_test": [
            "1",
            "5",
            "7",
            "9",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_18",
            "public_19"
        ],
        "count_neg": 8,
        "count_pos": 12,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3107.1.txt",
            "test/in.3107.2.txt",
            "test/in.3107.3.txt",
            "test/in.3107.4.txt",
            "test/in.3107.5.txt",
            "test/in.3107.6.txt",
            "test/in.3107.7.txt",
            "test/in.3107.8.txt",
            "test/in.3107.9.txt",
            "test/in.3107.public_10.txt",
            "test/in.3107.public_11.txt",
            "test/in.3107.public_12.txt",
            "test/in.3107.public_13.txt",
            "test/in.3107.public_14.txt",
            "test/in.3107.public_15.txt",
            "test/in.3107.public_16.txt",
            "test/in.3107.public_17.txt",
            "test/in.3107.public_18.txt",
            "test/in.3107.public_19.txt",
            "test/in.3107.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 99,
        "subject": "Lab-9",
        "bug_id": "3107-300579",
        "binary_path": "300579",
        "source_file": "300579_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "2",
            "3",
            "4",
            "6",
            "8",
            "public_16",
            "public_17"
        ],
        "passing_test": [
            "1",
            "5",
            "7",
            "9",
            "public_10",
            "public_11",
            "public_12",
            "public_13",
            "public_14",
            "public_15",
            "public_18",
            "public_19",
            "public_20"
        ],
        "count_neg": 7,
        "count_pos": 13,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3107.1.txt",
            "test/in.3107.2.txt",
            "test/in.3107.3.txt",
            "test/in.3107.4.txt",
            "test/in.3107.5.txt",
            "test/in.3107.6.txt",
            "test/in.3107.7.txt",
            "test/in.3107.8.txt",
            "test/in.3107.9.txt",
            "test/in.3107.public_10.txt",
            "test/in.3107.public_11.txt",
            "test/in.3107.public_12.txt",
            "test/in.3107.public_13.txt",
            "test/in.3107.public_14.txt",
            "test/in.3107.public_15.txt",
            "test/in.3107.public_16.txt",
            "test/in.3107.public_17.txt",
            "test/in.3107.public_18.txt",
            "test/in.3107.public_19.txt",
            "test/in.3107.public_20.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    },
    {
        "id": 100,
        "subject": "Lab-9",
        "bug_id": "3108-300755",
        "binary_path": "300755",
        "source_file": "300755_buggy.c",
        "reference_file": "Main.c",
        "line_numbers": [],
        "failing_test": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "public_11",
            "public_12",
            "public_14",
            "public_15",
            "public_16",
            "public_17",
            "public_18",
            "public_19",
            "public_20"
        ],
        "passing_test": [
            "public_10",
            "public_13",
            "public_8",
            "public_9"
        ],
        "count_neg": 16,
        "count_pos": 4,
        "crash_input": "",
        "exploit_file_list": [
            "test/in.3108.1.txt",
            "test/in.3108.2.txt",
            "test/in.3108.3.txt",
            "test/in.3108.4.txt",
            "test/in.3108.5.txt",
            "test/in.3108.6.txt",
            "test/in.3108.7.txt",
            "test/in.3108.public_10.txt",
            "test/in.3108.public_11.txt",
            "test/in.3108.public_12.txt",
            "test/in.3108.public_13.txt",
            "test/in.3108.public_14.txt",
            "test/in.3108.public_15.txt",
            "test/in.3108.public_16.txt",
            "test/in.3108.public_17.txt",
            "test/in.3108.public_18.txt",
            "test/in.3108.public_19.txt",
            "test/in.3108.public_20.txt",
            "test/in.3108.public_8.txt",
            "test/in.3108.public_9.txt"
        ],
        "test_timeout": 5,
        "bug_type": "Test Failure",
        "language": "c",
        "config_script": "config_subject",
        "build_script": "build_subject",
        "test_script": "run_test",
        "pvt_test_script": "run_private_tests.sh"
    }
]
